# Generated by Django 4.1.3 on 2022-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='same_slug',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
