# Generated by Django 4.1.3 on 2022-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_car_name_product_same_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='same_slug',
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='same_part_number',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
